ALTER TABLE provider_observations
    DROP CONSTRAINT IF EXISTS chk_provider_observations_metric;

ALTER TABLE provider_observations
    ADD CONSTRAINT chk_provider_observations_metric CHECK (
        metric_code IN (
            'precipitation',
            'temperature',
            'wind_speed',
            'cloudiness',
            'ndvi',
            'ndre',
            'ndmi',
            'cloud_mask',
            'humidity_rh',
            'cloud_total',
            'pressure_msl',
            'radiation',
            'soil_moisture'
        )
    );

CREATE TABLE IF NOT EXISTS api_algorithm_runs (
    run_id TEXT PRIMARY KEY,
    field_id BIGINT NOT NULL REFERENCES fields (id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    algorithm_id TEXT NOT NULL,
    algorithm_version TEXT NOT NULL,
    range_start TIMESTAMPTZ NOT NULL,
    range_end TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'OK',
    reason TEXT,
    error_code TEXT,
    inputs_used JSONB NOT NULL DEFAULT '{}'::jsonb,
    quality_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_payload JSONB,
    created_by BIGINT REFERENCES app_users (id) ON DELETE SET NULL,
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_api_algorithm_runs_source CHECK (source IN ('Copernicus', 'NASA', 'Mock')),
    CONSTRAINT chk_api_algorithm_runs_status CHECK (status IN ('OK', 'INSUFFICIENT_DATA', 'FAILED')),
    CONSTRAINT chk_api_algorithm_runs_range CHECK (range_end >= range_start)
);

CREATE INDEX IF NOT EXISTS idx_api_algorithm_runs_field_algo
    ON api_algorithm_runs (field_id, algorithm_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_algorithm_runs_status
    ON api_algorithm_runs (status, created_at DESC);

WITH sources(source) AS (
    VALUES ('Copernicus'), ('NASA'), ('Mock')
),
layers(layer_id, title_ru, category, value_type, units, time_available, default_granularity, spatial_modes, grid_sizes_m, zoom_rules, legend, quality_rules) AS (
    VALUES
        (
            'weather.temp_2m',
            'Температура воздуха (2 м)',
            'weather',
            'scalar',
            'C',
            ARRAY['hour','day','month']::text[],
            'day',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"gradient","min":-30,"max":45}'::jsonb,
            'Сырые данные температуры, агрегируются по выбранной гранулярности'
        ),
        (
            'weather.humidity_rh',
            'Относительная влажность',
            'weather',
            'scalar',
            '%',
            ARRAY['hour','day','month']::text[],
            'day',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"gradient","min":0,"max":100}'::jsonb,
            'Сырые данные влажности из провайдера'
        ),
        (
            'weather.precip_sum',
            'Осадки (сумма)',
            'precip',
            'scalar',
            'mm',
            ARRAY['hour','day','month']::text[],
            'day',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"bins","thresholds":[0,1,5,10,20,40]}'::jsonb,
            'Сумма осадков за период'
        ),
        (
            'weather.cloud_total',
            'Общая облачность',
            'weather',
            'scalar',
            '%',
            ARRAY['hour','day','month']::text[],
            'hour',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"gradient","min":0,"max":100}'::jsonb,
            'Сырая облачность/оценка покрытия'
        ),
        (
            'weather.pressure_msl',
            'Давление на уровне моря',
            'weather',
            'scalar',
            'hPa',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:250"}'::jsonb,
            '{"type":"gradient","min":980,"max":1040}'::jsonb,
            'Сырой погодный параметр, доступность зависит от источника'
        ),
        (
            'weather.radiation',
            'Солнечная радиация',
            'weather',
            'scalar',
            'W/m2',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:250"}'::jsonb,
            '{"type":"gradient","min":0,"max":1200}'::jsonb,
            'Сырая радиация, используется в расчётах ET0'
        ),
        (
            'weather.wind_speed_10m',
            'Скорость ветра (10 м)',
            'atmo_dynamics',
            'scalar',
            'm/s',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['field','grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"speed_scale","min":0,"max":30}'::jsonb,
            'Сырая скорость ветра'
        ),
        (
            'weather.wind_vector_10m',
            'Ветер (вектор 10 м)',
            'atmo_dynamics',
            'vector',
            'm/s',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"speed_scale","min":0,"max":30}'::jsonb,
            'Вектор ветра формируется из скорости и направления'
        ),
        (
            'weather.vorticity_index',
            'Индекс вихревости',
            'atmo_dynamics',
            'scalar',
            'index',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['grid','tiles']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"grid:100"}'::jsonb,
            '{"type":"gradient","min":0,"max":1}'::jsonb,
            'Derived-индекс по динамике ветра, без метеообъектов-level обещаний'
        ),
        (
            'soil.moisture',
            'Влажность почвы',
            'soil',
            'scalar',
            '%',
            ARRAY['hour','day']::text[],
            'day',
            ARRAY['field','grid','tiles','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"gradient","min":0,"max":100}'::jsonb,
            'Сырая влажность почвы, если доступна от источника'
        ),
        (
            'soil.moisture_anomaly',
            'Аномалия влажности почвы',
            'soil',
            'scalar',
            '%',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['field','grid','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"field","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"diverging","min":-50,"max":50}'::jsonb,
            'Derived: отклонение от базовой нормы поля'
        ),
        (
            'soil.trafficability_risk',
            'Риск проходимости техники',
            'risk',
            'scalar',
            'index',
            ARRAY['hour','day']::text[],
            'day',
            ARRAY['field','grid','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"field","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"risk","min":0,"max":1}'::jsonb,
            'Derived: осадки + влажность почвы'
        ),
        (
            'sat.ndvi',
            'NDVI',
            'satellite',
            'raster',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['grid','tiles','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"gradient","min":0,"max":1}'::jsonb,
            'Сырые спутниковые индексы'
        ),
        (
            'sat.ndre',
            'NDRE',
            'satellite',
            'raster',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['grid','tiles','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"gradient","min":0,"max":1}'::jsonb,
            'Сырые спутниковые индексы'
        ),
        (
            'sat.ndmi',
            'NDMI',
            'satellite',
            'raster',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['grid','tiles','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"gradient","min":0,"max":1}'::jsonb,
            'Сырые спутниковые индексы'
        ),
        (
            'sat.scene_quality',
            'Качество спутниковой сцены',
            'risk',
            'contour',
            '%',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['grid','tiles']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"tiles"}'::jsonb,
            '{"type":"cloudiness","min":0,"max":100}'::jsonb,
            'Используются облачность/маска/флаги качества'
        ),
        (
            'sat.cloud_mask',
            'Облачность / маска',
            'risk',
            'contour',
            '%',
            ARRAY['hour','day']::text[],
            'hour',
            ARRAY['grid','tiles']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"grid:1000","10-12":"grid:500","13-14":"grid:250",">=15":"tiles"}'::jsonb,
            '{"type":"cloudiness","min":0,"max":100}'::jsonb,
            'Низкое качество помечается как LOW_QUALITY'
        ),
        (
            'sat.growth_rate',
            'Скорость роста индекса',
            'satellite',
            'scalar',
            'index/day',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['field','grid','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"field","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"diverging","min":-0.2,"max":0.2}'::jsonb,
            'Derived по последовательности NDVI'
        ),
        (
            'sat.field_uniformity_cv',
            'Неоднородность поля (CV)',
            'satellite',
            'scalar',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['field','zones']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"field","10-12":"field",">=13":"zones"}'::jsonb,
            '{"type":"risk","min":0,"max":1}'::jsonb,
            'Derived по зональной вариативности'
        ),
        (
            'sat.anomaly_vs_baseline',
            'Аномалия относительно baseline',
            'satellite',
            'scalar',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['field','grid','zones']::text[],
            ARRAY[1000,500,250,100]::integer[],
            '{"z<=9":"field","10-12":"grid:500","13-14":"grid:250",">=15":"zones"}'::jsonb,
            '{"type":"diverging","min":-1,"max":1}'::jsonb,
            'Derived относительно 30-дневного baseline'
        ),
        (
            'sat.season_curve',
            'Сезонная кривая вегетации',
            'satellite',
            'scalar',
            'index',
            ARRAY['day','month']::text[],
            'day',
            ARRAY['field','zones']::text[],
            ARRAY[1000,500,250]::integer[],
            '{"z<=9":"field","10-12":"field",">=13":"zones"}'::jsonb,
            '{"type":"line"}'::jsonb,
            'Derived: начало/пик/спад сезона'
        )
)
INSERT INTO api_layer_registry (
    layer_id,
    source,
    title_ru,
    category,
    value_type,
    units,
    time_available,
    default_granularity,
    max_lookback_days,
    spatial_modes,
    grid_sizes_m,
    zoom_rules,
    legend,
    has_quality_flags,
    quality_rules,
    status
)
SELECT
    l.layer_id,
    s.source,
    l.title_ru,
    l.category,
    l.value_type,
    l.units,
    l.time_available,
    l.default_granularity,
    30,
    l.spatial_modes,
    l.grid_sizes_m,
    l.zoom_rules,
    l.legend,
    TRUE,
    l.quality_rules,
    'OK'
FROM layers l
CROSS JOIN sources s
ON CONFLICT (layer_id, source) DO UPDATE
SET
    title_ru = EXCLUDED.title_ru,
    category = EXCLUDED.category,
    value_type = EXCLUDED.value_type,
    units = EXCLUDED.units,
    time_available = EXCLUDED.time_available,
    default_granularity = EXCLUDED.default_granularity,
    max_lookback_days = EXCLUDED.max_lookback_days,
    spatial_modes = EXCLUDED.spatial_modes,
    grid_sizes_m = EXCLUDED.grid_sizes_m,
    zoom_rules = EXCLUDED.zoom_rules,
    legend = EXCLUDED.legend,
    has_quality_flags = EXCLUDED.has_quality_flags,
    quality_rules = EXCLUDED.quality_rules,
    status = EXCLUDED.status,
    updated_at = NOW();
